# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI/CD

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  lint:
    name: Linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - name: Setup Python
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: poetry
      - name: Install dependencies
        run: |
          poetry install --only="linting"
      - name: wemake-python-styleguide
        uses: wemake-services/wemake-python-styleguide@0.18.0
        with:
          reporter: 'github-pr-review'
          path: './extended_enum'
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}

  test:
    strategy:
      matrix:
        python: ["3.8", "3.9", "3.10", "3.11"]
      fail-fast: false
    
    name: "Test on Python ${{ matrix.python }}"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Poetry
        run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: "${{ matrix.python }}"
          cache: poetry
      - name: Install dependencies
        run: |
          poetry install --only="main,testing"
      - name: Execute tests
        run: poetry run pytest --junitxml=pytest.xml --cov-report=term-missing --cov-report=xml:pytest_coverage.xml --cov-config=pyproject.toml ./tests
    
